### ISSUE TITLE
libcore.io.ErrnoException: open failed: EACCES (Permission denied)

### ISSUE THREAD

**Issue by matthewn4444** [matthewn4444/onscripter-plus-android#7]
```bash
java.io.IOException: open failed: EACCES (Permission denied)
at java.io.File.createNewFile(File.java:946)
at com.onscripter.plus.VNPreferences$LoadSaveSettingsTask.doInBackground(VNPreferences.java:376)
at com.onscripter.plus.VNPreferences$LoadSaveSettingsTask.doInBackground(VNPreferences.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: open failed: EACCES (Permission denied)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
at java.io.File.createNewFile(File.java:939)
... 8 more
java.io.IOException: open failed: EACCES (Permission denied)
at java.io.File.createNewFile(File.java:946)
at com.onscripter.plus.VNPreferences$LoadSaveSettingsTask.doInBackground(VNPreferences.java:376)
at com.onscripter.plus.VNPreferences$LoadSaveSettingsTask.doInBackground(VNPreferences.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: libcore.io.ErrnoException: open failed: EACCES (Permission denied)
at libcore.io.Posix.open(Native Method)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
at java.io.File.createNewFile(File.java:939)
... 8 more

```

**Comment by Volcanoscar** [comment]
Facing the same problem here ,Dude , how did you solve it ?

**Comment by matthewn4444** [comment]
It was creating a file on sd card with Android 4.4 and higher. I fixed by not saving it on sdcard.
